### ISSUE TITLE
The ability to link items in chat does not work

### ISSUE THREAD

**Issue by weaz12** [jubiman/DeviousDiscord#10]
Not sure if this broke with 1.20....but ATM9 is the first pack in a while where this functionality did not work.

Typically, to link an item you would hover over it and press Shift+T and it would link it in game chat.

**Comment by jubiman** [comment]
Seems like this is related to Quark (the mod adding item sharing) not being updated to 1.20. See: [reddit](https://www.reddit.com/r/QuarkMod/comments/147jscc/how_long_before_version_120/) and [curseforge](https://www.curseforge.com/minecraft/mc-mods/quark).

Since it requires the mod to be present on the client-side as well, I'm afraid this won't be possible.
If you have other ideas feel free to open this issue again.

**Comment by weaz12** [comment]
https://www.curseforge.com/minecraft/mc-mods/showcase-item

Can this be used instead?
